---
abstract: 'Dist::Zilla configuration the way SILEX does it'
author:
  - '김도형 - Keedi Kim <keedi@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::More: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-SILEX
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - public
  package:
    - DB
provides:
  Dist::Zilla::PluginBundle::SILEX:
    file: lib/Dist/Zilla/PluginBundle/SILEX.pm
    version: v0.0.2
  Pod::Weaver::PluginBundle::SILEX:
    file: lib/Pod/Weaver/PluginBundle/SILEX.pm
    version: v0.0.2
requires:
  Dist::Zilla: '5'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.133360'
  Dist::Zilla::PluginBundle::DAGOLDEN: '0.062'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Dist::Zilla::Util: '0'
  List::MoreUtils: '0'
  Moose: '0.99'
  Pod::Weaver::PluginBundle::DAGOLDEN: '0'
  autodie: '2.00'
  namespace::autoclean: '0.09'
  perl: '5.006'
resources:
  bugtracker: https://github.com/silexkr/dist-zilla-pluginbundle-silex/issues
  homepage: https://github.com/silexkr/dist-zilla-pluginbundle-silex
  repository: https://github.com/silexkr/dist-zilla-pluginbundle-silex.git
version: v0.0.2
x_authority: cpan:SILEX
